USE CLL;
-- DELETE FROM imagenesfabricacion WHERE ID > 17;

insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-1.webp','/bateas/arg/batea-1-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-3.webp','/bateas/ch/batea-3-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-isla-1.webp',null);
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-3.webp','/bateas/arg/batea-3-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-8.webp','/bateas/ch/batea-8-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-isla-3.webp','/bateas/arg/batea-isla-3-2.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-5.webp','/bateas/arg/batea-5-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-6.webp','/bateas/arg/batea-6-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-isla-2.webp','/bateas/ch/batea-isla-2-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-isla-7.webp','/bateas/arg/batea-isla-7-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-12.webp','/bateas/ch/batea-12-3.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-recta-1.webp','/bateas/ch/batea-recta-1-3.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-8.webp','/bateas/arg/batea-8-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-9.webp',null);
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-18.webp',null);
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-10.webp','/bateas/arg/batea-10-1.webp');
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-11.webp',null);
insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-recta-1.webp','/bateas/arg/batea-recta-2.webp');

SELECT * FROM imagenesfabricacion;

-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-2.webp','/bateas/arg/batea-2-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-5.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-2.webp','/bateas/ch/batea-2-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-14.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-7.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-recta-4.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-isla-1-1.webp','/bateas/ch/batea-isla-1-2.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-17.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-16-1.webp','/bateas/ch/batea-16.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-6.webp','/bateas/ch/batea-6-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-7.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-4.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-11-1.webp','/bateas/ch/batea-10.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-14.webp','/bateas/ch/batea-14-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-14.webp','/bateas/ch/batea-14-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-13.webp','/bateas/ch/batea-13-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-12.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-13.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-15.webp','/bateas/arg/batea-15-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-19.webp','/bateas/ch/batea-19-1.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-16.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/ch/batea-recta-2-1.webp','/bateas/ch/batea-recta-2.webp');
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-18.webp',null);
-- insert into imagenesfabricacion(producto,imageUrl,imageUrl2) values ('bateas','/bateas/arg/batea-18.webp',null);